Skip to content
plankanban
/
planka

Type / to search

Code
Issues
207
Pull requests
12
Discussions
Actions
Projects
Security
Insights
Build and push Docker image
v1.15.2 #61
Jobs
Run details
Workflow file for this run
.github/workflows/build-and-push-docker-image.yml at da63598
name: Build and push Docker image

on:
  release:
    types: [created]

jobs:
  build-and-push-docker-image:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        uses: actions/github-script@v6
        id: set-version
        with:
          result-encoding: string
          script: return context.payload.release.tag_name.replace('v', '')

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: |
            ghcr.io/plankanban/planka:latest
            ghcr.io/plankanban/planka:${{ steps.set-version.outputs.result }}
chore: Update version · plankanban/planka@da63598
